services:
  - type: web
    name: my-backend
    env: node
    branch: main
    plan: free
    rootDir: /
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: EMAIL_USER
        value: your-email@domain.com
      - key: EMAIL_PASS
        value: your-email-password
